# Generated by Django 6.0.4 on 2026-05-04 21:01

import secrets

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_profile_referral_codes(apps, schema_editor):
    Profile = apps.get_model("Users", "Profile")
    for p in Profile.objects.all():
        if getattr(p, "referral_code", None):
            continue
        for _ in range(64):
            c = secrets.token_hex(4).upper()
            if not Profile.objects.filter(referral_code=c).exists():
                Profile.objects.filter(pk=p.pk).update(referral_code=c)
                break


class Migration(migrations.Migration):

    dependencies = [
        ("Admins", "0002_ticket_owner_user"),
        ("Users", "0003_auction_seller_user_auction_seller_wallet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="referral_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referral_signups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(populate_profile_referral_codes, migrations.RunPython.noop),
        migrations.AddField(
            model_name="ticketpurchase",
            name="discount_percent_applied",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="ticketpurchase",
            name="promo_code_used",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="EventWaitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("offered", "Offered"),
                            ("fulfilled", "Fulfilled"),
                            ("missed", "Missed payment window"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="Admins.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_waitlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=40, unique=True)),
                ("discount_percent", models.FloatField()),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("uses_count", models.PositiveIntegerField(default=0)),
                ("per_user_limit", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admins.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromoRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Admins.event"
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="Users.promocode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferralCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percent", models.FloatField()),
                ("consumed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_credits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaitlistOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(db_index=True, unique=True)),
                ("unit_price_eth", models.FloatField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="Users.eventwaitlist",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_offers",
                        to="Admins.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="eventwaitlist",
            constraint=models.UniqueConstraint(
                fields=("user", "event"), name="unique_waitlist_user_event"
            ),
        ),
        migrations.AddIndex(
            model_name="promoredemption",
            index=models.Index(
                fields=["user", "promo"], name="Users_promo_user_id_c5af85_idx"
            ),
        ),
    ]
